site_name: Documentation
docs_dir: .
use_directory_urls: false
repo_name: "bzd"
repo_url: "https://github.com/blaizard/bzd"

nav:
  - Home: README.md
  - BDL:
    - Overview: docs/bdl/overview.md
    - Syntax: docs/bdl/syntax.md
    - Components: docs/bdl/components.md
    - Composition: docs/bdl/composition.md
    - Executors: docs/bdl/executors.md
    - Gateway: docs/bdl/gateway.md
    - System: docs/bdl/system.md
  - Bazel:
    - bdl: bazel-out/k8-fastbuild/bin/docs/api/bazel/bdl.md
    - cc: bazel-out/k8-fastbuild/bin/docs/api/bazel/cc.md
    - docker: bazel-out/k8-fastbuild/bin/docs/api/bazel/docker.md
    - documentation: bazel-out/k8-fastbuild/bin/docs/api/bazel/documentation.md
    - nodejs: bazel-out/k8-fastbuild/bin/docs/api/bazel/nodejs.md
    - nodejs_web: bazel-out/k8-fastbuild/bin/docs/api/bazel/nodejs_web.md
    - package: bazel-out/k8-fastbuild/bin/docs/api/bazel/package.md
  - C++:
    - Directory Layout: cc/README.md
    - Core:
      - Async: cc/bzd/core/async/README.md

theme:
  name: material
  palette:
    primary: "blue grey"
    accent: "light blue"

plugins:
  - exclude:
      glob:
        - external/*
        - bazel-out/**/*.runfiles/*
        - bazel-out/**/tools/bazel_build/rules/assets/documentation/builder
        - bazel-out/**/tools/bazel_build/rules/assets/documentation/mkdocs_wrapper
        - tools/bazel_build/rules/assets/documentation/builder.py
        - tools/bazel_build/rules/assets/documentation/mkdocs_wrapper.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
